name = "fosdem"
version = "0.1.0"
description = "A Gleam project"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.26"
lustre = "~> 1.3"
gleam_json = "~> 0.5"
lustre_websocket = "~> 0.5"
gleam_http = "~> 3.1"

[dev-dependencies]
gleeunit = "~> 0.10"
