name = "fosdem"
version = "0.1.0"
description = "A Gleam project"
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.26"
gleam_json = "~> 0.5"
gleam_erlang = "~> 0.17"
gleam_otp = "~> 0.5"
mist = "~> 0.9"
gleam_http = "~> 3.1"
glisten = "~> 0.6"

[dev-dependencies]
gleeunit = "~> 0.10"
